spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flance
    username: postgres
    password: franksam
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
